export const headerLinks = [
    {
      label: 'Create Event',
      route: '/',
    },
    {
      label: 'Profile',
      route: '/',
    },
    {
      label: 'Settings',
      route: '/',
    },
  ]

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "About Us", url: "/" },
      { title: "FAQs", url: "/" },
      { title: "Terms of Use", url: "/" },
      { title: "Get Started", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Careers", url: "/" },
      { title: "Newsroom", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
      { title: "LinkedIn", url: "/" }
    ],
  },
];

export const filters = [
  { name: "Cooking Classes", image: "kitchen" },
  { name: "Yoga & Meditation", image: "self_improvement" },
  { name: "Art & Creativity", image: "palette" },
  { name: "Music & Dance", image: "music_note" },
  { name: "Fitness & Wellness", image: "fitness_center" },
  { name: "Language Learning", image: "language" },
  { name: "Virtual Tours", image: "explore" },
  { name: "Photography", image: "camera" },
  { name: "Cultural Experiences", image: "museum" },
  { name: "Outdoor Adventures", image: "terrain" },
  { name: "Mindfulness Sessions", image: "whatshot" },
  { name: "Cooking Demos", image: "restaurant_menu" },
  { name: "Live Music Performances", image: "music_video" },
  { name: "Art Workshops", image: "color_lens" },
  { name: "Dance Classes", image: "audiotrack" },
  { name: "Fitness Challenges", image: "directions_run" },
  { name: "Language Exchange", image: "forum" },
  { name: "Historical Tours", image: "history" },
  { name: "Virtual Reality Experiences", image: "3d_rotation" },
  { name: "Painting Sessions", image: "brush" },
  { name: "Concerts", image: "event" },
  { name: "Cooking Competitions", image: "local_dining" },
  { name: "Meditation Retreats", image: "nature_people" },
  { name: "Drawing Classes", image: "edit" },
  { name: "Running Clubs", image: "directions_run" },
  { name: "Language Lessons", image: "translate" },
  { name: "Nature Walks", image: "nature_people" },
  { name: "Live Theatre Performances", image: "theater_comedy" },
  { name: "Sculpture Workshops", image: "colorize" },
  { name: "Zumba Classes", image: "fitness_center" },
  { name: "Cooking Workshops", image: "restaurant_menu" },
  { name: "Gardening Sessions", image: "eco" },
  { name: "Architecture Tours", image: "architecture" },
  { name: "Online Concerts", image: "music_video" },
  { name: "Calligraphy Classes", image: "title" },
  { name: "Mountain Biking Adventures", image: "pedal_bike" },
  { name: "Yoga Retreats", image: "nature_people" },
  { name: "Pottery Making", image: "emoji_objects" },
  { name: "Dance Parties", image: "audiotrack" },
  { name: "HIIT Workouts", image: "fitness_center" },
  { name: "Language Clubs", image: "people" },
  { name: "City Tours", image: "location_city" },
  { name: "Live Comedy Shows", image: "emoji_events" },
  { name: "Digital Art Classes", image: "palette" },
  { name: "Surfing Lessons", image: "surfing" },
  { name: "Wine Tasting", image: "local_bar" },
  { name: "Acting Workshops", image: "theaters" },
  { name: "Diving Experiences", image: "pool" },
];
